### ISSUE TITLE
Render model resource problem.

### ISSUE THREAD

**Issue by dany5639** [ElDewrito/HaloOnlineTagTool#6]
Installing a render model and a previously setup mode tag over a build that already has custom models results in this: http://i.imgur.com/NGworPu.jpg .
The mode tag resource index doesn't match with the newly imported model?

**Comment by Shockfire** [comment]
Can you please give me some steps to reproduce this issue?

**Comment by XeCREATURE** [comment]
import a model using modeltest, then extract the mode tag "extract xxxx file". import the extracted mode tag into another modded tags.dat with imported models. Update- the issue is that when you import a mode tag file the resource address for the actual model in resourced.dat is incorrect.

**Comment by ihatecompvir** [comment]
I don't think this is necessarily a problem with tag tool itself, more a problem with how annoying the resource system is to deal with.

Here's a good visualization of what's happening:
You use modeltest to make a model, it imports into the cone mode tag which now points to resources.dat index 0x721
You extract the cone mode tag, still pointing to 0x721
You import it into a new tags/resources.dat, which already has 3 added models for a total of 0x724 resources in resources.dat
You import the model into resources.dat using modeltest, which places its new model resource at 0x725
The cone tag you imported, however, still points to 0x721, which is NOT the right resource index, so your geometry becomes broken

There's not really a good way to solve this problem without commands being created which facilitate importing a mode tag and a resource at the same time, which would also update the mode to point to the correct resource index.

**Comment by Shockfire** [comment]
@ihatecompvir is correct.

Yeah, I think the real issue here is that we need better support for model importing in general. The modeltest command is really just what it says...a test command. I intentionally made it create a new resource each time you inject because this makes it possible to inject multiple models by duplicating the street cone tag.

If you want to fix this issue for the purpose of your mod installers, you need to use the resourcedata command to overwrite the correct model resource.
